version: "3.9"

services:
  reddit-fetcher:
    build: .
    container_name: reddit-fetcher
    ports:
      - "${REDDIT_CALLBACK_PORT:-8080}:${REDDIT_CALLBACK_PORT:-8080}"  # Allows dynamic port assignment
    volumes:
      - ./data:/data
    environment:
      - FETCH_INTERVAL=${FETCH_INTERVAL:-3600}  # Runs every hour (default)
      - OUTPUT_FORMAT=${OUTPUT_FORMAT:-json}  # Default output format
      - REDDIT_CALLBACK_PORT=${REDDIT_CALLBACK_PORT:-8080}  # OAuth authentication port
      - PYTHONUNBUFFERED=1
    restart: unless-stopped